import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,signInAnonymously} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getDatabase,ref,set,get,onValue,update,remove,onDisconnect,runTransaction,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js';
import {firebaseConfig} from './firebase-config.js';

const $=s=>document.querySelector(s), screens=['#studentJoin','#teacherSetup','#lobby','#game','#results'];
const isTeacher=new URLSearchParams(location.search).get('role')==='teacher';
let auth,db,uid,roomCode='',room=null,quiz=null,timerId=null,lastQuestion=-1;
const session={hostSecret:sessionStorage.getItem('liveQuizHostSecret')||crypto.randomUUID(),nickname:''};
sessionStorage.setItem('liveQuizHostSecret',session.hostSecret);
function show(id){screens.forEach(s=>$(s).classList.toggle('hidden',s!==id))}
function message(id,text,ok=false){const el=$(id);el.textContent=text;el.className=ok?'ok':'error'}
function escapeText(v){return String(v??'').replace(/[<>]/g,'')}
function configured(){return firebaseConfig.apiKey&&!firebaseConfig.apiKey.includes('PASTE_')}
function validateQuiz(data){if(!data||typeof data.title!=='string'||!Array.isArray(data.questions)||!data.questions.length)throw Error('title과 questions가 필요합니다.');data.questions.forEach((q,i)=>{if(typeof q.question!=='string'||!Array.isArray(q.choices)||q.choices.length<2||q.choices.length>4||!Number.isInteger(q.answer)||q.answer<0||q.answer>=q.choices.length)throw Error(`${i+1}번 문제 형식이 올바르지 않습니다.`);q.timeLimit=Math.max(5,Math.min(120,Number(q.timeLimit)||20))});return data}
async function connect(){if(!configured())throw Error('firebase-config.js에 Firebase 설정을 먼저 입력해 주세요.');const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getDatabase(app);const cred=await signInAnonymously(auth);uid=cred.user.uid}
async function loadQuiz(text){quiz=validateQuiz(JSON.parse(text));$('#quizPreview').textContent=`${quiz.title} · ${quiz.questions.length}문제`;$('#createRoom').disabled=false;message('#teacherMessage','')}

$('#roleLink').textContent=isTeacher?'학생 화면':'선생님 화면';$('#roleLink').href=isTeacher?'./':'?role=teacher';show(isTeacher?'#teacherSetup':'#studentJoin');
$('#uploadTab').onclick=()=>{$('#uploadPanel').classList.remove('hidden');$('#pastePanel').classList.add('hidden');$('#uploadTab').classList.add('active');$('#pasteTab').classList.remove('active')};
$('#pasteTab').onclick=()=>{$('#uploadPanel').classList.add('hidden');$('#pastePanel').classList.remove('hidden');$('#pasteTab').classList.add('active');$('#uploadTab').classList.remove('active')};
$('#quizFile').onchange=async e=>{try{await loadQuiz(await e.target.files[0].text())}catch(err){message('#teacherMessage',err.message)}};
$('#loadText').onclick=()=>{try{loadQuiz($('#quizText').value)}catch(err){message('#teacherMessage',err.message)}};
$('#createRoom').onclick=async()=>{try{message('#teacherMessage','방을 만드는 중…',true);await connect();for(let i=0;i<12;i++){const code=String(Math.floor(10000+Math.random()*90000));const roomRef=ref(db,`rooms/${code}`);const result=await runTransaction(roomRef,current=>current===null?{hostId:uid,hostSecret:session.hostSecret,status:'lobby',quiz,currentQuestion:-1,reveal:false,createdAt:Date.now(),players:{}}:undefined,{applyLocally:false});if(result.committed){roomCode=code;watchRoom();return}}throw Error('빈 방 코드를 만들지 못했습니다. 다시 시도해 주세요.')}catch(err){message('#teacherMessage',err.message)}};
$('#joinForm').onsubmit=async e=>{e.preventDefault();try{roomCode=$('#roomCode').value.replace(/\D/g,'');session.nickname=$('#nickname').value.trim();if(!/^\d{5}$/.test(roomCode))throw Error('5자리 숫자 코드를 입력하세요.');await connect();const snap=await get(ref(db,`rooms/${roomCode}`));if(!snap.exists()||snap.val().status==='ended')throw Error('열려 있는 방을 찾지 못했습니다.');const playerRef=ref(db,`rooms/${roomCode}/players/${uid}`);await set(playerRef,{name:session.nickname.slice(0,12),score:0,online:true,joinedAt:serverTimestamp()});onDisconnect(playerRef).update({online:false});watchRoom()}catch(err){message('#joinMessage',err.message)}};
function watchRoom(){onValue(ref(db,`rooms/${roomCode}`),snap=>{if(!snap.exists()){alert('방이 종료되었습니다.');location.href='./';return}room=snap.val();renderRoom()});}
function isHost(){return isTeacher&&room?.hostId===uid&&room?.hostSecret===session.hostSecret}
function renderRoom(){clearInterval(timerId);if(room.status==='lobby'){show('#lobby');$('#lobbyCode').textContent=roomCode;$('#lobbyTitle').textContent=room.quiz.title;$('#lobbyHint').textContent=isHost()?'학생이 모두 들어오면 시작하세요.':'선생님이 곧 퀴즈를 시작합니다.';renderPlayers();$('#startQuiz').classList.toggle('hidden',!isHost());$('#connectionText').textContent='실시간 연결됨'}else if(room.status==='question'||room.status==='revealed'){renderQuestion()}else if(room.status==='results'){renderResults()}}
function renderPlayers(){const players=Object.values(room.players||{});$('#playerList').replaceChildren(...players.map(p=>{const el=document.createElement('span');el.className='pill';el.textContent=`${p.online===false?'○':'●'} ${escapeText(p.name)}`;return el}));if(!players.length)$('#playerList').textContent='아직 입장한 학생이 없습니다.'}
$('#startQuiz').onclick=()=>update(ref(db,`rooms/${roomCode}`),{status:'question',currentQuestion:0,reveal:false,questionStartedAt:Date.now()});
function renderQuestion(){show('#game');const index=room.currentQuestion,q=room.quiz.questions[index],revealed=room.status==='revealed'||room.reveal;$('#gameCode').textContent=`${roomCode} · ${index+1}/${room.quiz.questions.length}`;$('#progressBar').style.width=`${(index+1)/room.quiz.questions.length*100}%`;$('#questionText').textContent=q.question;const answer=room.players?.[uid]?.answers?.[index];$('#choices').replaceChildren(...q.choices.map((choice,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=choice;b.disabled=isHost()||answer!==undefined||revealed;if(answer===i)b.classList.add('selected');if(revealed)b.classList.add(i===q.answer?'correct':answer===i?'wrong':'');b.onclick=()=>submitAnswer(i);return b}));$('#hostControls').classList.toggle('hidden',!isHost());$('#revealAnswer').classList.toggle('hidden',revealed);$('#nextQuestion').classList.toggle('hidden',!revealed);$('#nextQuestion').textContent=index===room.quiz.questions.length-1?'결과 보기':'다음 문제';const answers=Object.values(room.players||{}).filter(p=>p.answers?.[index]!==undefined).length;$('#answerStatus').classList.toggle('hidden',!isHost()&&!revealed);$('#answerStatus').textContent=isHost()?`${answers}/${Object.keys(room.players||{}).length}명 응답`:(revealed?(answer===q.answer?'정답입니다!':'아쉬워요. 정답을 확인하세요.'):'답을 제출했습니다.');startTimer(q.timeLimit,room.questionStartedAt,revealed);lastQuestion=index}
function startTimer(limit,started,revealed){if(revealed){$('#timer').textContent='정답 공개';return}const tick=()=>{const left=Math.max(0,limit-Math.floor((Date.now()-started)/1000));$('#timer').textContent=`${left}초`;if(!left){clearInterval(timerId);if(isHost())reveal()}};tick();timerId=setInterval(tick,500)}
async function submitAnswer(choice){const q=room.quiz.questions[room.currentQuestion],elapsed=Math.max(0,(Date.now()-room.questionStartedAt)/1000),bonus=choice===q.answer?Math.max(500,Math.round(1000-(elapsed/q.timeLimit)*500)):0;const playerRef=ref(db,`rooms/${roomCode}/players/${uid}`);await runTransaction(playerRef,p=>{if(!p||p.answers?.[room.currentQuestion]!==undefined)return;p.answers=p.answers||{};p.answers[room.currentQuestion]=choice;p.score=(p.score||0)+bonus;return p})}
async function reveal(){await update(ref(db,`rooms/${roomCode}`),{status:'revealed',reveal:true})}
$('#revealAnswer').onclick=reveal;
$('#nextQuestion').onclick=()=>{const next=room.currentQuestion+1;if(next>=room.quiz.questions.length)update(ref(db,`rooms/${roomCode}`),{status:'results'});else update(ref(db,`rooms/${roomCode}`),{status:'question',currentQuestion:next,reveal:false,questionStartedAt:Date.now()})};
function renderResults(){show('#results');const players=Object.entries(room.players||{}).map(([id,p])=>({id,...p})).sort((a,b)=>(b.score||0)-(a.score||0));$('#ranking').replaceChildren(...players.map((p,i)=>{const el=document.createElement('div');el.className='rank-item';el.innerHTML=`<span>${i+1}. ${escapeText(p.name)}</span><span>${p.score||0}점</span>`;return el}));const me=room.players?.[uid];$('#myResult').innerHTML=!isHost()&&me?`<div class="score">${me.score||0}</div><p>수고했어요, ${escapeText(me.name)}!</p>`:'';$('#resultControls').classList.toggle('hidden',!isHost())}
$('#restartQuiz').onclick=()=>{const updates={status:'lobby',currentQuestion:-1,reveal:false};Object.keys(room.players||{}).forEach(id=>{updates[`players/${id}/score`]=0;updates[`players/${id}/answers`]=null});update(ref(db,`rooms/${roomCode}`),updates)};
$('#closeRoom').onclick=async()=>{if(confirm('방을 종료할까요?'))await remove(ref(db,`rooms/${roomCode}`))};
